### ISSUE TITLE
One DarkArduino doesn't work with Arduino IDE 1.8.13

### ISSUE THREAD

**Issue by dietzste** [konrad91/OneDarkArduino#6]
Hey there!
I really would like to use this dark theme! I think it's one of the best themes out there! Unfortunatly, overwriting the theme folder doesn't seem to work anymore with **Arduino IDE 1.8.13**. This also applys to JeffThompsons [Dark Arduino Theme](https://github.com/jeffThompson/DarkArduinoTheme#note).

I also tried the suggested solution shown in this [YouTube Video](https://www.youtube.com/watch?v=puuOu03p__0&feature=youtu.be). It shows the zip-File in the theme drop-down menu, but when I select it and restart Arduino IDE, I still get the white theme.

As the the repo [Readme](https://github.com/konrad91/OneDarkArduino#creating-your-own-mods) suggest... *the newest version of the Arduino IDE makes creating custom themes trickier* - but the further explaination leaves me in the dark to be honest.

Can somebody help fixing this theme?

**Comment by Docteh** [comment]
I followed those instructions but with 7-zip and it seems to work fine. 
[OneDarkArduino.zip](https://github.com/konrad91/OneDarkArduino/files/6049253/OneDarkArduino.zip)

![image](https://user-images.githubusercontent.com/190571/109294030-87863a80-77e1-11eb-9e18-00091c2b1bb2.png)

**Comment by dietzste** [comment]
> 
> I followed those instructions but with 7-zip and it seems to work fine.
> [OneDarkArduino.zip](https://github.com/konrad91/OneDarkArduino/files/6049253/OneDarkArduino.zip)

You are right! I seem to have missed the step, where I had to zip the theme folder again. My bad.

@Docteh Which tool did you use to create the zip-file of the subfolder?

**Comment by Docteh** [comment]
I just go into the theme folder, select all of the files, and in the right click menu I get an option from 7-zip to add to a .zip

![image](https://user-images.githubusercontent.com/190571/109302816-a63efe00-77ee-11eb-9123-f455e27f5911.png)

**Comment by dietzste** [comment]
> I just go into the theme folder, select all of the files, and in the right click menu I get an option from 7-zip to add to a .zip

@Docteh. Sorry, I meant the zip-link you provided above. I'm asking because the normal interface of github only privides - as far as I know - links of the entire repo. Your link is a zip-link of a subfolder though. Which tool or webpage did you use to create the subfolder zip file link?

**Comment by Docteh** [comment]
Oh, that. I just uploaded the zip off of my computer into the github comment box.

**Comment by dietzste** [comment]
> 
> 
> Oh, that. I just uploaded the zip off of my computer into the github comment box.

😃  - OK!

**Comment by dietzste** [comment]
OK, to close the issue - the solution as shown in the [Youtube-Video](https://www.youtube.com/watch?v=puuOu03p__0&feature=youtu.be) by FabryStyle works as follows:

1. Download the zip link provided by @Docteh [above](https://github.com/konrad91/OneDarkArduino/files/6049253/OneDarkArduino.zip) OR
   - [Download](https://github.com/konrad91/OneDarkArduino/archive/master.zip)  OneDarkArduino repo
   - Unzip file
   - Zip content of the theme folder
2. Paste zip file into Arduino lib folder (e.g. in Windows: C:\Program Files (x86)\Arduino\lib\theme)
3. Start Arduino program:  choose Preferences > Theme and select zip file
4. Restart Arduino
5. Done
>

**Comment by dietzste** [comment]
works as provided
